version: "3.9"

services:
  fuspay:
    image: simple_crud
    build: .
    ports:
      - "4000:4000"
    env_file:
      - ./.env
    depends_on:
      - db
    command: bash -c 'sh ./start.sh'
  db:
    image: postgres:13
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=simple_crud
    ports:
      - "5432:5432"

volumes:
  postgres_data: